# -*- coding: utf-8 -*-
"""detectyolo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12jF1jxMwhn_l_7AkRMCQiERP9c7SL75a

# **Mount Drive**
"""

from google.colab import drive

drive.mount('/content/gdrive')

ROOT_DIR = "/content/gdrive/My Drive/Fire Evacuation/datasets/hazardousdetect"

!pip install ultralytics

"""Train YOLOV8 Model"""

import os
from ultralytics import YOLO

# Load pre trained model
model = YOLO("yolov8n.pt")

# train the model
results = model.train(data=os.path.join(ROOT_DIR, "hazardousdata.yaml"), epochs=80)

"""# **Copy result into drive**"""

import shutil
source = '/content/runs/detect/train12'
destination = '/content/gdrive/My Drive/Fire Evacuation/datasets/hazardousdetect/runs/epoch 50'
shutil.copytree(source, destination)

import os
from ultralytics import YOLO

# Load pre trained model
model = YOLO("yolov8n.pt")

# train the model
results = model.train(data=os.path.join(ROOT_DIR, "hazardousdata.yaml"), epochs=10)

import os
from ultralytics import YOLO

# Load pre trained model
model = YOLO("yolov8n.pt")

# train the model
results = model.train(data=os.path.join(ROOT_DIR, "hazardousdata.yaml"), epochs=20)

import os
from ultralytics import YOLO

# Load pre trained model
model = YOLO("yolov8n.pt")

# train the model
results = model.train(data=os.path.join(ROOT_DIR, "hazardousdata.yaml"), epochs=30)

import os
from ultralytics import YOLO

# Load pre trained model
model = YOLO("yolov8n.pt")

# train the model
results = model.train(data=os.path.join(ROOT_DIR, "hazardousdata.yaml"), epochs=40)

import os
from ultralytics import YOLO

# Load pre trained model
model = YOLO("yolov8n.pt")

# train the model
results = model.train(data=os.path.join(ROOT_DIR, "hazardousdata.yaml"), epochs=50)

"""# **Detecting in user input**"""

import ultralytics
from google.colab import drive
drive.mount('content/mdrive')

from ultralytics import YOLO
import matplotlib.pyplot as plt
import cv2

# Load trained YOLOv8 model
model = YOLO("/content/mdrive/My Drive/Fire Evacuation/results/flammable_detect_yolo/70 epochs/weights/best.pt")

# Load the image
image_path = "/content/mdrive/My Drive/Fire Evacuation/sample.jpg"
img = cv2.imread(image_path)

results = model(image_path)

result_img = results[0].plot()

plt.imshow(cv2.cvtColor(result_img, cv2.COLOR_BGR2RGB))
plt.axis('off')
plt.show()

